//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1DV402.S1.L02C.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_1DV402.S1.L02C.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ange det udda antalet asterisker (max 79) i diamantens midja..
        /// </summary>
        internal static string enterNumberMsg {
            get {
                return ResourceManager.GetString("enterNumberMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FEL! Det inmatade värdet är inte ett udda heltal mellan 1 och {0}.
        /// </summary>
        internal static string errorMessage {
            get {
                return ResourceManager.GetString("errorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tryck tangent för att fortsätta - Esc avslutar..
        /// </summary>
        internal static string escapeOrResumeMsg {
            get {
                return ResourceManager.GetString("escapeOrResumeMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kunde inte tolkas som ett giltigt nummer..
        /// </summary>
        internal static string userInputCouldNotParseMsg {
            get {
                return ResourceManager.GetString("userInputCouldNotParseMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FEL:.
        /// </summary>
        internal static string userInputErrorMsg {
            get {
                return ResourceManager.GetString("userInputErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Det inmatade värdet är inte ett udda heltal..
        /// </summary>
        internal static string userInputValueNotOddMsg {
            get {
                return ResourceManager.GetString("userInputValueNotOddMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to är ett för högt värde..
        /// </summary>
        internal static string userInputValueTooLargeMsg {
            get {
                return ResourceManager.GetString("userInputValueTooLargeMsg", resourceCulture);
            }
        }
    }
}
